{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "9f9be230-4ae9-4689-9337-003d4e97d63b",
   "metadata": {},
   "source": [
    "# Claro loop + fit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "634780a6-fe78-4124-b27c-f056056b65e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "from claro_fit import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1cd6dfaf-a3b5-4758-84d7-d3b5f5d4c656",
   "metadata": {},
   "outputs": [
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "The default subfolders' paths are *Station_1__*\\Station_1__??_Summary\\Chip_???\\S_curve.\n",
      "The default file names are Ch_*_offset_*_Chip_*.txt.\n",
      "To confirm, press Enter. Press any other key to change the paths.\n",
      " \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_218\\S_curve\\Ch_2_offset_0_Chip_218.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_219\\S_curve\\Ch_2_offset_0_Chip_219.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_241\\S_curve\\Ch_1_offset_0_Chip_241.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_247\\S_curve\\Ch_0_offset_0_Chip_247.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_251\\S_curve\\Ch_0_offset_0_Chip_251.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_255\\S_curve\\Ch_0_offset_0_Chip_255.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_257\\S_curve\\Ch_0_offset_0_Chip_257.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__11\\Station_1__11_Summary\\Chip_259\\S_curve\\Ch_7_offset_0_Chip_259.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__13\\Station_1__13_Summary\\Chip_138\\S_curve\\Ch_1_offset_0_Chip_138.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__13\\Station_1__13_Summary\\Chip_147\\S_curve\\Ch_0_offset_0_Chip_147.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__13\\Station_1__13_Summary\\Chip_161\\S_curve\\Ch_0_offset_0_Chip_161.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_012\\S_curve\\Ch_0_offset_0_Chip_012.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_014\\S_curve\\Ch_0_offset_0_Chip_014.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_016\\S_curve\\Ch_1_offset_0_Chip_016.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_021\\S_curve\\Ch_0_offset_0_Chip_021.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_046\\S_curve\\Ch_0_offset_0_Chip_046.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_054\\S_curve\\Ch_1_offset_0_Chip_054.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_076\\S_curve\\Ch_0_offset_0_Chip_076.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_084\\S_curve\\Ch_0_offset_0_Chip_084.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__15\\Station_1__15_Summary\\Chip_213\\S_curve\\Ch_0_offset_0_Chip_213.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__18\\Station_1__18_Summary\\Chip_061\\S_curve\\Ch_0_offset_0_Chip_061.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__18\\Station_1__18_Summary\\Chip_193\\S_curve\\Ch_0_offset_0_Chip_193.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__18\\Station_1__18_Summary\\Chip_226\\S_curve\\Ch_0_offset_0_Chip_226.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__18\\Station_1__18_Summary\\Chip_227\\S_curve\\Ch_0_offset_0_Chip_227.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__19\\Station_1__19_Summary\\Chip_018\\S_curve\\Ch_0_offset_0_Chip_018.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__19\\Station_1__19_Summary\\Chip_032\\S_curve\\Ch_0_offset_0_Chip_032.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__20\\Station_1__20_Summary\\Chip_100\\S_curve\\Ch_0_offset_0_Chip_100.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__20\\Station_1__20_Summary\\Chip_140\\S_curve\\Ch_0_offset_0_Chip_140.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_080\\S_curve\\Ch_0_offset_0_Chip_080.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_126\\S_curve\\Ch_0_offset_0_Chip_126.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_128\\S_curve\\Ch_0_offset_0_Chip_128.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_181\\S_curve\\Ch_0_offset_0_Chip_181.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_209\\S_curve\\Ch_0_offset_0_Chip_209.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__24\\Station_1__24_Summary\\Chip_213\\S_curve\\Ch_4_offset_0_Chip_213.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__25\\Station_1__25_Summary\\Chip_042\\S_curve\\Ch_0_offset_0_Chip_042.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__25\\Station_1__25_Summary\\Chip_161\\S_curve\\Ch_6_offset_0_Chip_161.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__27\\Station_1__27_Summary\\Chip_034\\S_curve\\Ch_3_offset_0_Chip_034.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__27\\Station_1__27_Summary\\Chip_199\\S_curve\\Ch_0_offset_0_Chip_199.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__27\\Station_1__27_Summary\\Chip_254\\S_curve\\Ch_0_offset_0_Chip_254.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__33\\Station_1__33_Summary\\Chip_081\\S_curve\\Ch_2_offset_0_Chip_081.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__33\\Station_1__33_Summary\\Chip_085\\S_curve\\Ch_0_offset_0_Chip_085.txt. First line: Troppi dati\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__33\\Station_1__33_Summary\\Chip_128\\S_curve\\Ch_0_offset_0_Chip_128.txt. First line: Troppi datia. Going on...\n",
      "ValueError: Bad data in: C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__34\\Station_1__34_Summary\\Chip_192\\S_curve\\Ch_4_offset_0_Chip_192.txt. First line: Troppi datia. Going on...\n",
      "Reading C:\\Users\\MARTINA\\Desktop\\secondolotto_1\\Station_1__36\\Station_1__36_Summary\\Chip_259\\S_curve\\Ch_7_offset_0_Chip_259.txt\\Ch_0_offset_0_Chip_180.txt. Going on...\n",
      "Process completed in 97.04 s.\n",
      "\n",
      "Total number of files found: 41461.\n",
      "Total number of good files: 40911. Output paths to good files are stored in claro_files.txt\n",
      "Total number of bad files: 550. Output paths to bad files are stored in bad_files.txt\n"
     ]
    }
   ],
   "source": [
    "a = fileinfo('C:\\\\Users\\\\MARTINA\\\\Desktop\\\\secondolotto_1\\\\')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "fc82c090-6034-4cf4-b186-1a5d75147e26",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'C:\\\\Users\\\\MARTINA\\\\Desktop\\\\secondolotto_1\\\\Station_1__11\\\\Station_1__11_Summary\\\\Chip_002\\\\S_curve\\\\Ch_1_offset_0_Chip_002.txt'"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "fileinfo_find(a, chip='002', ch='1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "dadc4ef0-7ed1-40f0-a095-fcfced0e8be7",
   "metadata": {},
   "outputs": [],
   "source": [
    "def plot_fit(x, y, metafit, fileinfo, npoints=1000,\n",
    "             interactive=False,\n",
    "             show_scatter=True, show_fit=True, show_transition=True,\n",
    "             save=False, save_path='.\\plot', save_format='pdf', show=True,\n",
    "             **kwargs):\n",
    "    \"\"\"\n",
    "    [Function documentation]\n",
    "    \"\"\"\n",
    "    \n",
    "\n",
    "    title = f\"Fit CLARO: station {fileinfo['station']}, chip {fileinfo['chip']}, ch {fileinfo['ch']}\"\n",
    "\n",
    "    try:\n",
    "        if metafit['code']=='bad':\n",
    "            raise ValueError(\"Error: the provided fit has invalid parameters. \"\n",
    "                             +f\"Plot {title} will not be plotted.\\r\")\n",
    "            \n",
    "        font = {\n",
    "            'fontsize': plt.rcParams['axes.titlesize'],\n",
    "            'fontweight' : plt.rcParams['axes.titleweight'],\n",
    "            'verticalalignment': 'baseline',\n",
    "            # 'horizontalalignment': plt.loc,\n",
    "        }\n",
    "        \n",
    "        plt.figure(figsize=(5,5), tight_layout=True)\n",
    "        plt.title(title, fontdict=font)\n",
    "    \n",
    "        # x,y data computed as a grid of npoints and using parameters of the fit\n",
    "        fit_params = metafit['params']\n",
    "        fit_errs = metafit['errors']\n",
    "        \n",
    "        xfit = np.linspace(x.min(), x.max(), npoints)\n",
    "        yfit= func(xfit, *fit_params)\n",
    "        \n",
    "        # Show scatterplot of data (default = True)\n",
    "        if show_scatter == True:\n",
    "            plt.scatter(x, y, label='Data points', zorder=2)\n",
    "            plt.annotate(f\"From data file\\nTransition = {fileinfo['transition']:.2f}\\n\"\n",
    "                         +f\"Width = {fileinfo['width']:.2f}\",\n",
    "                         xy=(0.025, .975), xycoords='axes fraction',\n",
    "                         verticalalignment='top', color='gray', alpha=0.8)\n",
    "            plt.xlabel('x [arb units]', fontdict=font)\n",
    "            plt.ylabel('y [arb units]', fontdict=font)\n",
    "            # plt.legend(loc='lower right', fontsize = 8)\n",
    "        \n",
    "                             \n",
    "        # Show plot of fit (default = True)\n",
    "        if show_fit == True: \n",
    "            plt.plot(xfit, yfit, label='erf fit', zorder=1, color='r', alpha=0.8)\n",
    "            plt.annotate(f\"Fit parameters\\nAmplitude = ({fit_params[0]:.2f}\"+r\" $\\pm$ \"+f\"{fit_errs[0]:.2f})\\n\"\n",
    "                         +f\"Transition = ({fit_params[1]:.2f}\"+r\" $\\pm$ \"+f\"{fit_errs[1]:.2E})\\n\"\n",
    "                         +f\"Width = ({fit_params[2]*2:.2f}\"+r\" $\\pm$ \"+f\"{fit_errs[2]*2:.2E})\",\n",
    "                         xy=(0.025, .3), xycoords='axes fraction', verticalalignment='top',\n",
    "                         color='r', alpha=0.8,\n",
    "                         bbox=dict(boxstyle=\"square\", fc=\"white\", ec=\"black\", lw=1, alpha=0.8))\n",
    "            \n",
    "        # Show transition point\n",
    "        if show_transition == True:\n",
    "            xtrans = fit_params[1]\n",
    "            ytrans = func(xtrans, *fit_params)\n",
    "            plt.scatter(xtrans, ytrans, s=100, c='darkred', marker='*',\n",
    "                        zorder=2, label='Transition point')\n",
    "            plt.vlines(x=xtrans, ymin=y[0], ymax=y[-1], linestyles='dashed',\n",
    "                        alpha=0.5, zorder=1)\n",
    "            plt.hlines(y=ytrans, xmin=x[0], xmax=x[-1], linestyles='dashed',\n",
    "                        alpha=0.5, zorder=1)\n",
    "            plt.annotate(f\"Transition = {fit_params[1]:.2f}\\nWidth = {fit_params[2]*2:.2f}\", \n",
    "                         xy=(0.025, .6), xycoords='axes fraction', verticalalignment='top',)\n",
    "\n",
    "    except ValueError as err: \n",
    "        if interactive==True: print(err)\n",
    "    \n",
    "    if save == True:\n",
    "        plt.savefig(save_path+'.'+save_format)\n",
    "    \n",
    "    if show == True:\n",
    "        plt.show()\n",
    "    else:\n",
    "        plt.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "32781b0b-28c2-4e6d-9cc1-efbd53c96a84",
   "metadata": {},
   "outputs": [],
   "source": [
    "def func(x, ampl, a, b):\n",
    "    \"\"\"Modified erf function.\n",
    "    \n",
    "    Amplitude ampl and shift on the vertical axis ampl/2,\n",
    "    inflection point at a, normalization proportional to b.\n",
    "    Deafult guesses are [AMPLITUDE, TRANSITION, AMPLITUDE/2].\n",
    "    \"\"\"\n",
    "    \n",
    "    return ampl/2*(1+sp.erf((x-a)/(b*np.sqrt(2))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7d146490-e4cf-4abc-b98e-7df273208f56",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n",
      "C:\\Anaconda3\\envs\\oop\\lib\\site-packages\\scipy\\optimize\\minpack.py:833: OptimizeWarning: Covariance of the parameters could not be estimated\n",
      "  warnings.warn('Covariance of the parameters could not be estimated',\n",
      "C:\\Users\\MARTINA\\Desktop\\OOPROJECT\\pyproj\\branch_claro\\Def\\claro_fit.py:193: RuntimeWarning: invalid value encountered in sqrt\n",
      "  except ValueError as err:\n"
     ]
    }
   ],
   "source": [
    "tot = 0\n",
    "counter = 0\n",
    "for file in a.values(): # file is the sub-dict, access keys via file['key']\n",
    "    tot += 1\n",
    "    x,y,meta = read_data(file['path'])\n",
    "    metafit = fit_erf(x,y,meta, interactive=False)\n",
    "    plot_fit(x, y, metafit, fileinfo=file, show=False, show_fit=True, show_transition=True, save=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "oop",
   "language": "python",
   "name": "oop"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
